### ISSUE TITLE
Create a simple express app

### ISSUE THREAD

**Issue by Shobhit-Mishra-02** [chaudhary0007/Ecommerce#2]
Now, you have to develop an Express js app.
Where it should return `Hi` when a `GET` request is made at `/`

Example:
let's say your app is running at `localhost:5000`
then, if I make a `GET` request to `http://localhost:5000/` it should return `Hi`

Here is the link of docs: https://expressjs.com/en/starter/hello-world.html

**Comment by Shobhit-Mishra-02** [comment]
One more thing, whenever you make a commit to a particular issue, please do not forget to add its ID in the commit message.

Example:
let's say you are done with the development of a simple express app,
then you could make a commit like this: `git commit -m "added a simple express app #2"`, here #2 is the ID of the issue. Look carefully at the title of the issue, you will get the ID just after that.

Even if you would hover on #2 you will get to know why it makes sense.

**Comment by chaudhary0007** [comment]
Ok Done and From the next time i will add the Id also

**Comment by Shobhit-Mishra-02** [comment]
well done :+1: 

But still, there are a few things that I would like to tell you about your code.

1. Your task was to create a root route which means `/`, but you created a `/hello` route. So please change `/hello` to `/`
2. Second, thing is that I highly recommend you use prettier for code formatting, here is the [link](https://www.digitalocean.com/community/tutorials/how-to-format-code-with-prettier-in-visual-studio-code) follow the docs and configure prettier in your vs code.

Note: *If you have installed prettier, so put your prettier to format code on save mode, this mode will make your dev experience smooth*

**Comment by chaudhary0007** [comment]
changes done  and also i formatted it with prettier

**Comment by Shobhit-Mishra-02** [comment]
So this issue has been resolved :100:
