### ISSUE TITLE
Adding packages in your express app

### ISSUE THREAD

**Issue by Shobhit-Mishra-02** [chaudhary0007/Ecommerce#3]
Now, your task is to add packages to your express app to make it more suitable for complex applications like e-commerce.

Here is a link to a [tutorial](https://medium.com/@agavitalis/setting-up-a-nodejs-express-application-with-babel-642fe0dd45a5) this will help you to install all the required packages for your express app.

So, what you are going to install
1. Nodemon: this is a package that will help you reload the app if any change happens to your files.
2. body-parser: this is a parser that helps to parse the JSON input because plain express code does not have the default nature to handle incoming JSON.
3. cors: cross-origin resource, in simple words, you can control who can access your API.

**Comment by Shobhit-Mishra-02** [comment]
OK, there is one more thing that you are going to install babel, babel is a transpiler that helps you to convert ES6 to old JS versions.

**Comment by Shobhit-Mishra-02** [comment]
If you want to know more about each package you can google for their npm registry :+1:

**Comment by chaudhary0007** [comment]
Done

**Comment by Shobhit-Mishra-02** [comment]
There is an issue with your code. When I ran `npm run start`, it threw an error saying nodemon not found.
Please check your package.json file because it does not contain the nodemon module.

**Comment by chaudhary0007** [comment]
check

**Comment by Shobhit-Mishra-02** [comment]
Nice, it's working now :+1:
