### ISSUE TITLE
Add middleware in express app

### ISSUE THREAD

**Issue by Shobhit-Mishra-02** [chaudhary0007/Ecommerce#4]
## Task

Study about the middleware in express js from [docs](https://expressjs.com/en/guide/using-middleware.html)
After that, you have to add a route-level middleware which should print the method, and route on the console whenever a request is made to the API.

Example:
let's say  your app is running at `localhost:5000`
So whenever a `GET` request is made to `localhost:500/`, in the console `Method: GET    Path: /` should be printed.

*Let me tell you the solution to this problem is written in the docs, so please read it carefully and try it on your side as well.*

**Comment by chaudhary0007** [comment]
done

**Comment by Shobhit-Mishra-02** [comment]
Nice, it is working as expected.
