### ISSUE TITLE
Babel is not working 

### ISSUE THREAD

**Issue by Shobhit-Mishra-02** [chaudhary0007/Ecommerce#5]
I was running your app then I noticed one thing that...
ES6 is not working in this project, so what happens when I use `import` keyword it breaks the code, which should not happen if we are using Babel.

Please resolve this issue first, @chaudhary0007.

**Comment by chaudhary0007** [comment]
ok i check it and resolve that bug

**Comment by Shobhit-Mishra-02** [comment]
Now, it's working
