### ISSUE TITLE
Study mongodb and mongoose package

### ISSUE THREAD

**Issue by Shobhit-Mishra-02** [chaudhary0007/Ecommerce#7]
## Task
Now, the time come to study the database, since we have selected MongoDB as our database. Quickly go through the mongoose and MongoDB docs.
1. First setup MongoDB in your machine and study the basic command in MongoDB, to learn MongoDB follow this youtube video [link](https://www.youtube.com/watch?v=J6mDkcqU_ZE)
2. So, after learning basic MongoDB, you are ready to learn about the Mongoose package, actually Mongoose is a package that works as a wrapper around your MongoDB server, which makes your development easy. [docs](https://mongoosejs.com/)

*You start learning, I will also add a small code snippet which help you to understand how we are going to work in express with MongoDB*

**Comment by chaudhary0007** [comment]
done
